name: ci - docker-test

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      docker_test_matrix:
        description: "Json matrix for docker test"
        required: true
        type: string

jobs:
  docker-test:
    env:
      arch_type: ${{ matrix.arch_type }}
    runs-on: ${{ matrix.build_host }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.docker_test_matrix) }}

    steps:
      - name: Register QEMU emulators
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: create test file
        run: |
          echo "--- Creating source file ---"
          cat > hello.c << 'EOF'
          #include <stdio.h>
          int main() {
              printf("Hello World!\n");
              return 0;
          }
          EOF

      - name: bootstrap
        run: >
          docker run -v ${{ github.workspace }}:/root -w /root ghcr.io/userdocs/qbt-musl-cross-make:${arch_type} bash -c '
          echo "--- Checking compiler ---" &&
          file /usr/local/bin/${arch_type}-gcc &&
          echo "--- Checking compiler symlinks work ---" &&
          /usr/local/bin/gcc -v'

      - name: Run cross-arch container gcc info
        run: >
          docker run -v ${{ github.workspace }}:/root -w /root ghcr.io/userdocs/qbt-musl-cross-make:${arch_type} bash -c '
          echo "--- Checking compiler ---" &&
          file /usr/local/bin/${arch_type}-gcc &&
          /usr/local/bin/gcc -v'

      - name: Run cross-arch container gcc build
        run: >
          docker run -v ${{ github.workspace }}:/root -w /root ghcr.io/userdocs/qbt-musl-cross-make:${arch_type} bash -c '
          echo "--- Compiling binary ---" &&
          gcc -static -o hello hello.c'

      - name: Run cross-arch container qemu run
        run: >
          docker run -v ${{ github.workspace }}:/root -w /root ghcr.io/userdocs/qbt-musl-cross-make:${arch_type} bash -c '
          echo "--- Checking binary type ---" &&
          file ./hello &&

          echo "--- Running binary ---" &&
          ./hello'
