name: ci - docker-test

on:
  workflow_call:
    inputs:
      docker_test_matrix:
        description: "Json matrix for docker test"
        required: true
        type: string

jobs:
  docker-test:
    runs-on: ${{ matrix.build_host }}
    container: ghcr.io/userdocs/qbt-musl-cross-make:${{ matrix.arch_type }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.docker_test_matrix) }}

    steps:
      - name: file gcc
        env:
          arch_type: ${{ matrix.arch_type }}
        run: file /usr/local/bin/${arch_type}-gcc

      - name: gcc -v
        env:
          arch_type: ${{ matrix.arch_type }}
        run: /usr/local/bin/${arch_type}-gcc -v

      - name: Create Hello World source
        run: |
          cat > hello.c << 'EOF'
          #include <stdio.h>
          int main() {
              printf("Hello World!\n");
              return 0;
          }
          EOF

      - name: Compile static Hello World binary
        env:
          arch_type: ${{ matrix.arch_type }}
        run: |
          gcc -static -o hello hello.c

      - name: file hello
        run: file ./hello

      - name: Test Hello World binary
        run: ./hello
