name: matrix musl-cross-make and release

on:
  - workflow_dispatch

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Host - wget musl-cross-make-master
        run: wget -qO musl-cross-make-master.tar.gz https://git.zv.io/toolchains/musl-cross-make/-/archive/master/musl-cross-make-master.tar.gz

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        id: upload
        with:
          name: musl-cross-make-master-archive
          path: musl-cross-make-master.tar.gz

  build:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: [musl-cross-make]
        os_id: [alpine]
        os_version_id: [edge]
        arch_type:
          [
            aarch64-linux-musl,
            aarch64_be-linux-musl,
            arm-linux-musleabi,
            arm-linux-musleabihf,
            armeb-linux-musleabi,
            armeb-linux-musleabihf,
            armel-linux-musleabi,
            armel-linux-musleabihf,
            armv5l-linux-musleabi,
            armv5l-linux-musleabihf,
            armv6-linux-musleabi,
            armv6-linux-musleabihf,
            armv7l-linux-musleabihf,
            armv7m-linux-musleabi,
            armv7r-linux-musleabihf,
            i486-linux-musl,
            i686-linux-musl,
            m68k-linux-musl,
            microblaze-linux-musl,
            microblazeel-linux-musl,
            mips-linux-musl,
            mips-linux-muslsf,
            mips-linux-musln32sf,
            mips64-linux-musl,
            mips64-linux-musln32,
            mips64-linux-musln32sf,
            mips64el-linux-musl,
            mips64el-linux-musln32,
            mips64el-linux-musln32sf,
            mipsel-linux-musl,
            mipsel-linux-musln32,
            mipsel-linux-musln32sf,
            mipsel-linux-muslsf,
            or1k-linux-musl,
            powerpc-linux-musl,
            powerpc-linux-muslsf,
            powerpc64-linux-musl,
            powerpc64le-linux-musl,
            powerpcle-linux-musl,
            powerpcle-linux-muslsf,
            riscv32-linux-musl,
            riscv64-linux-musl,
            s390x-linux-musl,
            sh2-linux-musl,
            sh2-linux-muslfdpic,
            sh2eb-linux-musl,
            sh2eb-linux-muslfdpic,
            sh4-linux-musl,
            sh4eb-linux-musl,
            x86_64-linux-musl,
            x86_64-linux-muslx32,
          ]

    name: ${{ matrix.name }} ${{ matrix.arch_type }}

    env:
      riscv32: "git-b76f37fd5625d038141b52184956fb4b7838e9a5"
      prerelease: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Host - phased updates
        run: echo 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates

      - name: Host - update
        run: sudo apt-get update

      - name: Host - upgrade
        run: sudo apt-get -y upgrade

      - name: Host - Install host qemu-static
        run: sudo apt-get install -y qemu binfmt-support qemu-user-static

      - name: Host - Docker multiarch bootstrap
        run: sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Host - Create docker multiarch container
        run: docker run --name multiarch -it -d -w /root -v ${{ github.workspace }}:/root ${{ matrix.os_id }}:${{ matrix.os_version_id }}

      - name: Docker - apk install build deps
        run: docker exec -w /root multiarch apk add autoconf automake bash bash-completion bison build-base cmake ccache curl findutils flex git graphviz libarchive-tools libtool linux-headers ncurses-dev patch perl pkgconf python3 python3-dev re2c rsync rsync tar texinfo ttf-freefont xz zip

      - name: Host - Download artifact - musl-cross-make-master
        uses: actions/download-artifact@v3
        id: download
        with:
          name: musl-cross-make-master-archive
          path: musl-cross-make-artifact-archive

      - name: Docker - Unpack musl-cross-make-master artifact
        run: docker exec -w /root/musl-cross-make-artifact-archive multiarch tar -xf musl-cross-make-master.tar.gz -C /root

      - name: Docker - Set riscv32 musl to ${{ env.riscv32 }}
        if: matrix.arch_type == 'riscv32-linux-musl'
        run: docker exec -w /root multiarch sed "s|MUSL_VER = git-master|MUSL_VER = ${{ env.riscv32 }}|" -i config.mak

      - name: Docker - Copy updated config.mak to build directory
        run: docker exec -w /root multiarch cp -f config.mak musl-cross-make-master/config.mak

      - name: Docker - install ${{ matrix.arch_type }} toolchain
        run: docker exec -w /root/musl-cross-make-master multiarch make -j"$(nproc)" install TARGET=${{ matrix.arch_type }} OUTPUT=/root/build/${{ matrix.arch_type }}

      - name: Docker - archive ${{ matrix.arch_type }} toolchain
        run: docker exec -w /root/build multiarch tar -czvf ${{ matrix.arch_type }}.tar.gz ${{ matrix.arch_type }}/

      - name: Host - set tag via date
        run: echo "github_tag=$(date +"%y%V")" >> $GITHUB_ENV

      - name: Host - set release info dynamically from config.mak
        run: printf "%s\n" "$(sed -rn "/CONFIG_SUB_REV = (.*)/,/LINUX_VER = (.*)/p" config.mak)" > realease_body.md

      - name: Create release - tag - assets
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: false
          artifacts: "build/${{ matrix.arch_type }}.tar.gz"
          replacesArtifacts: true
          tag: "${{ env.github_tag }}"
          name: "musl-cross-make toolchains"
          bodyFile: "realease_body.md"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: userdocs/mcm

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: userdocs/mcm:${{ matrix.arch_type }}
          build-args: |
            TARGET=${{ matrix.arch_type }}
            BASE_URL=https://github.com/userdocs/musl-cross-make/releases/latest/download
